### ISSUE TITLE
Improve exercises of Lab 6

### ISSUE THREAD

**Issue by cmoulliard** [gpe-mw-training/activemq-labs#10]
1) The Fabric A-MQ / camel exercise part of the lab has been created to cover Camel & AMQ using Karaf features and is not packaged as profile. The code must be refactored to : 
- Include a profile
- Push the content using fabric8:deploy maven goal 
- Package com.fusesource changed
- Camel route improved for the consumer

3) Add example about A-MQ Gateway

4) Add example using fabric a-mq discovery protocol with Apache Camel

**Comment by satyaj** [comment]
Fabric exercises not part of this course. They have been moved to the Fabric course.
