### ISSUE TITLE
Review failover & network of broker lab

### ISSUE THREAD

**Issue by cmoulliard** [gpe-mw-training/activemq-labs#2]
Review failover & network of broker lab
- Do we need all the config files of JBoss-AMQ or just activemq.xml is enough
- Could we use the these projects if we deploy them in JBoss-AMQ (openshift) ?

**Comment by cmoulliard** [comment]
just activemq.xml config is required

**Comment by satyaj** [comment]
Both labs now contain broker config file activemq.xml only.
