### ISSUE TITLE
Change version number of ActiveMQ

### ISSUE THREAD

**Issue by cmoulliard** [gpe-mw-training/activemq-labs#4]
As we have to move to A-MQ 6.2, we must change the version number defined within the parent pom

**Comment by satyaj** [comment]
Once we move the labs to OSEv3 and AMQ 6.2, we will use this version for the labs. Marking as enhancement.

**Comment by satyaj** [comment]
Fixed. 64296ca2e49d61ce63cb14e2995ed39b4c5938e8
